// <auto-generated />
using System;
using CryptoAlarmSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoAlarmSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260215190926_RemoveIsTriggeredUseStatus")]
    partial class RemoveIsTriggeredUseStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoAlarmSystem.Domain.Entities.Alarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlarmTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CryptoSymbolId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime?>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("TriggeredPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AlarmTypeId");

                    b.HasIndex("CryptoSymbolId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("Alarms");
                });

            modelBuilder.Entity("CryptoAlarmSystem.Domain.Entities.AlarmNotificationChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlarmId")
                        .HasColumnType("integer");

                    b.Property<int>("NotificationChannelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NotificationChannelId");

                    b.HasIndex("AlarmId", "NotificationChannelId")
                        .IsUnique();

                    b.ToTable("AlarmNotificationChannels");
                });

            modelBuilder.Entity("CryptoAlarmSystem.Domain.Entities.AlarmType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AlarmTypes");
                });

            modelBuilder.Entity("CryptoAlarmSystem.Domain.Entities.CryptoSymbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CryptoSymbols");
                });

            modelBuilder.Entity("CryptoAlarmSystem.Domain.Entities.NotificationChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("NotificationChannels");
                });

            modelBuilder.Entity("CryptoAlarmSystem.Domain.Entities.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlarmId")
                        .HasColumnType("integer");

                    b.Property<int>("AlarmTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("CryptoSymbolId")
                        .HasColumnType("integer");

                    b.Property<int>("NotificationChannelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TargetPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("TriggeredPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AlarmId");

                    b.HasIndex("AlarmTypeId");

                    b.HasIndex("CryptoSymbolId");

                    b.HasIndex("NotificationChannelId");

                    b.HasIndex("SentAt");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("CryptoAlarmSystem.Domain.Entities.Alarm", b =>
                {
                    b.HasOne("CryptoAlarmSystem.Domain.Entities.AlarmType", "AlarmType")
                        .WithMany("Alarms")
                        .HasForeignKey("AlarmTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CryptoAlarmSystem.Domain.Entities.CryptoSymbol", "CryptoSymbol")
                        .WithMany("Alarms")
                        .HasForeignKey("CryptoSymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlarmType");

                    b.Navigation("CryptoSymbol");
                });

            modelBuilder.Entity("CryptoAlarmSystem.Domain.Entities.AlarmNotificationChannel", b =>
                {
                    b.HasOne("CryptoAlarmSystem.Domain.Entities.Alarm", "Alarm")
                        .WithMany("AlarmNotificationChannels")
                        .HasForeignKey("AlarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoAlarmSystem.Domain.Entities.NotificationChannel", "NotificationChannel")
                        .WithMany("AlarmNotificationChannels")
                        .HasForeignKey("NotificationChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alarm");

                    b.Navigation("NotificationChannel");
                });

            modelBuilder.Entity("CryptoAlarmSystem.Domain.Entities.NotificationLog", b =>
                {
                    b.HasOne("CryptoAlarmSystem.Domain.Entities.Alarm", "Alarm")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("AlarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CryptoAlarmSystem.Domain.Entities.AlarmType", "AlarmType")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("AlarmTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CryptoAlarmSystem.Domain.Entities.CryptoSymbol", "CryptoSymbol")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("CryptoSymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CryptoAlarmSystem.Domain.Entities.NotificationChannel", "NotificationChannel")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("NotificationChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alarm");

                    b.Navigation("AlarmType");

                    b.Navigation("CryptoSymbol");

                    b.Navigation("NotificationChannel");
                });

            modelBuilder.Entity("CryptoAlarmSystem.Domain.Entities.Alarm", b =>
                {
                    b.Navigation("AlarmNotificationChannels");

                    b.Navigation("NotificationLogs");
                });

            modelBuilder.Entity("CryptoAlarmSystem.Domain.Entities.AlarmType", b =>
                {
                    b.Navigation("Alarms");

                    b.Navigation("NotificationLogs");
                });

            modelBuilder.Entity("CryptoAlarmSystem.Domain.Entities.CryptoSymbol", b =>
                {
                    b.Navigation("Alarms");

                    b.Navigation("NotificationLogs");
                });

            modelBuilder.Entity("CryptoAlarmSystem.Domain.Entities.NotificationChannel", b =>
                {
                    b.Navigation("AlarmNotificationChannels");

                    b.Navigation("NotificationLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
